# Intro to NumPy

NumPy is a python library for performing linear algebra calculations. It's also the foundation for many other libraries we'll be using in this course.

The first step to using a library is to import it:

In [0]:
import numpy as np

In [0]:
aa=list(range(1,11))
print('aa is of type: ',type(aa))
aa 

aa is of type:  <class 'list'>


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Once it's imported as `np`, we can use `np.array` to create a numpy array, which is like a python list, but with added functionality.

In [0]:
aa_nparray=np.array(aa)
print('aa_nparray is of type: ',type(aa_nparray))
aa_nparray

aa_nparray is of type:  <class 'numpy.ndarray'>


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Now that we have a list, let's check out some of these convenience methods.

## Basic Stats
We can use `mean()` to get the average of the numbers in the  numpy array:

In [0]:
np.mean(aa_nparray)

5.5

We can use `min()` and `max()` to grab the smallest and largest numbers in the array, respectively.

In [0]:
min(aa_nparray)

1

In [0]:
max(aa_nparray)

10

`argmin()` and `argmax()` will give you the **index** of the smallest and largest numbers in the array, respectively.

In [0]:
aa_nparray.argmin()

0

In [0]:
aa_nparray.argmax()

9

Numpy has a method for creating arrays from ranges of numbers: `np.arange`. It works like `range`, except it returns a numpy array as opposed to a vanilla python list.

In [0]:
numlist=np.arange(1,11)
numlist

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can compare two numpy arrays as follows. Can this be done with a Python list array?

In [0]:
if(numlist.all()==aa_nparray.all()):
    print('yes')

yes


In [0]:
bb=list(range(1,11))
if(aa.all() == bb.all()):
  print('yes')

AttributeError: ignored

# Broadcasting / Scalar Math

Exercise: Write a for loop to add 1 to each item in your list array

In [0]:
aa_add1=[]
for x in aa:
  x = x+1
  aa_add1.append(x)
# finish it with your code  
print(aa_add1)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


You are also use a compact from to loop for this purpose

In [0]:
aa_add1= [x+1 for x in aa]
aa_add1

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

With numpy, we no longer have to code for loops to do these types of calculations. We can simply broadcast our arithmetic operations across the entire array:

In [0]:
numlist_add1 = numlist + 1
print(numlist_add1)

[ 2  3  4  5  6  7  8  9 10 11]


We can also use broadcasting over a subset of an array:

In [0]:
(numlist[0:4]**2)

array([ 1,  4,  9, 16])

# Matrices vs Vectors

Vectors and matrices are used in Linear Algebra and Data Analtyics extensively. You can think of a **matrix** as an excel spreadsheet. A **vector** is a special kind of matrix in that it is a single column (or row)of data.

We can can use the `reshape` method to create a matrix from an array.

In [0]:
mm=np.arange(1,101)
print(mm)
matrix50=mm.reshape(10,10)
matrix3D=mm.reshape(5,5,4)
print(matrix50)
print(matrix3D) # 3D array
#find out about jagged array

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]]

 [[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]


# Transposing Matrices

Transposing is when a matrix is flipped along it's top-left to bottom-right diagonal. We use `T` on a numpy array to accomplish this task.

In [0]:
matrix50.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

# Slicing

Slicing numpy arrays is similar to slicing lists. We can get a single item by using bracket notation. 

**Practice:** Create a numpy array and grab the second item from that array.

In [0]:
nparray = np.array(range(1,51))
nparray[1]

2

You can also slice an array using a range of indices.

**Practice:** Grab the second through fifth items from your array.

In [0]:
nparray[1:5]

array([2, 3, 4, 5])

# Slicing Matrices

We still use bracket notation for slicing matrices, only now we separate our row slicing from column slicing with a comma.

In [0]:
yy=matrix50[:,7:8]
yy

array([[ 8],
       [18],
       [28],
       [38],
       [48],
       [58],
       [68],
       [78],
       [88],
       [98]])

# Boolean Selection

We can broadcast a boolean expression to filter a numpy array:

In [0]:
matrix46= matrix50[(matrix50>46)&(matrix50<56)]
print(matrix46)
type(matrix46)

[47 48 49 50 51 52 53 54 55]


numpy.ndarray

In [0]:
odd_cond= matrix50%2==1
matrix50[odd_cond]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# Views vs Copy

## no copy

In [0]:
a10=np.arange(1,11)
b10 = a10 # no copy, change in value and shape affect both
b10[2] = 20
print(a10[2])   # is a10 value got changed ?
b10.shape = 2,5
a10.shape # a10 shape also got changed?


20


(2, 5)

## view (shallow copy)

In [0]:
a10=np.arange(1,11)
b10view = a10.view() # shallow copy: change in value affect both but not shape
b10view[3]=30
print(a10[3])
b10view.shape = 2,5
a10.shape

30


(10,)

## copy (deep copy)

In [0]:
a10=np.arange(1,11)
b10copy = a10.copy()#copy: two copies of data does not affect each other in value or shape change
b10copy[2]=20
print(a10[2])
b10copy.shape = 2,5
a10.shape

3


(10,)